server:
  port: 7001

  root-path: /orbit

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_orbit?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  messages:
    basename: i18n/messages
    cache-seconds: -1
  mvc:
    dispatch-options-request: true
  data:
    mybatis:
      beforeMapperLocations: classpath*:mappers/**/*.xml

shiro:
  loginUrl: /login

orbit:
  cors:
    mapping: /**
    allow-credentials: true
    allowed-headers: Authorization, content-type
    allowed-methods: GET,POST,PUT,DELETE,PATCH
    allowed-origins: http://127.0.0.1:4200
    max-age: 3600
  i18n:
    resource-cache: false