server:
  context-path: /orbit

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_webapp?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

shiro:
  loginUrl: /login

